config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'articles/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "articles#index"

  get 'articles', to: 'articles#index'
  get 'articles/create', to: 'articles#new'
  get 'articles/:id', to: 'articles#show'
  get 'articles/:id/edit', to: 'articles#edit'
  get 'articles', to: 'articles#create'
  patch 'articles/:id', to: 'articles#update', as: :article
  post 'articles', to: 'articles#create'
  delete 'articles/:id', to: 'articles#destroy', as: :articles_destoy
  
  get 'users/:user_id/articles', to: 'articles#user_articles'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    
    has_rich_text :content

    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :find_article, except: [:index, :new, :create, :user_articles]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
  end

  def edit
  end

  def create
    # @article = Article.create(title: params[:article][:title], content: params[:article][:content], user: current_user)
    @article = current_user.articles.create(title: params[:article][:title], content: params[:article][:content], user: current_user)
    render json: @article
  end

  def update
    @article.update(title: params[:article][:title], content: params[:article][:content])
    redirect_to @article
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def user_articles
    @user = User.find(params[:user_id])
    render 'articles/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card mt-5 px-5 py-3">
    <h3 class="text-uppercase"><%= article.title %></h3>
    <p class="text-secondary">Author: <%= article.user.email %></p>
    <p class="text-secondary"><%= article.created_at %></p>
    <div class="row">
        <div class="col-2">
            <%= link_to 'View more', article %>
        </div>
        <div class="col-2">
            <% if user_signed_in? %>
                <%= button_to 'Delete', articles_destoy_path(article), method: :delete,  class: 'btn btn-danger btn-sm' %>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/articles/edit.html.erb
<%= render 'articles/form' %>

<div>
    <%= link_to "View article", @article %>
</div>

<div>
    <%= link_to "Delete article", @article, method: :delete %>
</div>

app/views/articles/index.html.erb
<% if user_signed_in? %>
    <h1>Hi <%= current_user.email %></h1>
<% end %>

<h3>
    <%= @user && @user.id != current_user.id ? "Articles by: #{@user.email}" : "My articles" %>
</h3>    
<%= render @user ? @user.articles : @articles %>

app/views/articles/new.html.erb
<%= render 'articles/form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div><%= @article.content %></div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <div class="container mt-5">
      <% if notice %>
        <p class="notice alert alert-primary"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Carmine</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Articles', articles_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'New article', articles_create_path, class:'nav-link' %>
        </li>
    </ul>
        <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, local: true }, class:"navbar-text" %>
        <% else %>
            <%= link_to "Iniciar sesión", new_user_session_path, class:"navbar-text" %> / 
            <%= link_to "Registro", new_user_registration_path, class:"navbar-text" %>
        <% end %>
  </div>
</nav>